cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update', views.cart_update, name="cart_update"),
]

catalogue/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('', views.CatalogueView.as_view(), name="catalogue"),
    path('<int:pk>/', views.VinylDetail.as_view(), name="vinyldetail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += [
    path('', include('home.urls', namespace='main')),
    path('users/', include('users.urls'), name='users'),
    path('catalogue/', include('catalogue.urls'), name='catalogue'),
    path('cart/', include('cart.urls'), name='cart'),
    path('mediaplayer/', include('mediaplayer.urls'), name='mediaplayer'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from catalogue.models import VinylRecord
from django.http import JsonResponse

def cart_summary(request):
    cart = Cart(request)
    cart_vinyls = cart.get_prods
    # cart_vinyls = cart.get_prods()
    return render(request, "cart/cart_summary.html", {"cart_vinyls": cart_vinyls})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        vinyl_id = int(request.POST.get('vinyl_id'))
        #поиск винил в бд
        vinyl = get_object_or_404(VinylRecord, id=vinyl_id)
        #сохранить в сессию
        cart.add(vinyl=vinyl)
        response = JsonResponse({'Vinyl Name: ': vinyl.title})
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        vinyl_id = int(request.POST.get('vinyl_id'))
        cart.delete(vinyl=vinyl_id)
        response = JsonResponse({'vinyl': vinyl_id})
        return response


def cart_update(request): # думаю нам это не надо и уже как будто будет лишним
    pass

templates/cart/cart_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping Cart</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>

<h1 class="mt-5 pt-5">
    <!-- <span style="color: rgb(215, 204, 204);">Shopping Cart</span><br> -->
    <strong><span style="color: rgb(18, 6, 6);">View your cart</span></strong>
</h1>

<div class="container">
    {% if cart_vinyls %}
        {% for vinyl in cart_vinyls %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ vinyl.cover.url }}" class="img-fluid rounded-start" alt="{{ vinyl.title }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ vinyl.title }}</h5>
                            <p class="card-text">{{ vinyl.artist }}</p>
                            <p class="card-text">{{ vinyl.price }}$</p>
                            <p class="card-text">{{ vinyl.description }}</p>
                            <p>Songs:</p>
                            {% for audio in vinyl.audio_files.all %}
                                <div>
                                    <h4>{{ audio.title }}</h4>
                                </div>
                            {% endfor %}
                            <p class="card-text"><small class="text-body-secondary">ID: {{ vinyl.id }}</small></p>
                            <a href="{% url 'catalogue:catalogue' %}" class="btn btn-primary">Home</a>
                            <button type="button" data-index="{{ vinyl.id }}" class="btn btn-danger delete-vinyl">Remove Vinyl</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>There is nothing in your cart</p>
    {% endif %}
</div>

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Vinylon</p>
    </div>
</footer>
{% endblock %}

<script>
    $(document).ready(function() {
        // тут прверка нажатия и удаление
        $('#test').click(function() {
            alert('Button clicked!');
        });

        $(document).on('click', '.delete-vinyl', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_delete" %}',
                data: {
                    vinyl_id: $(this).data('index'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(json) {
                    location.reload();
                },
                error: function(xhr, errmsg, err) {
                    console.error(xhr.status + ": " + xhr.responseText);
                }
            });
        });
    });
</script>

</body>
</html>