cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update', views.cart_update, name="cart_update"),
]

catalogue/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('', views.CatalogueView.as_view(), name="catalogue"),
    path('<int:pk>/', views.VinylDetail.as_view(), name="vinyldetail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += [
    path('', include('home.urls', namespace='main')),
    path('users/', include('users.urls'), name='users'),
    path('catalogue/', include('catalogue.urls'), name='catalogue'),
    path('cart/', include('cart.urls'), name='cart'),
    path('mediaplayer/', include('mediaplayer.urls'), name='mediaplayer'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView
from . import views

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

mediaplayer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "mediaplayer"

urlpatterns = [
    path('',  views.MediaPlayerView.as_view(), name="mediaplayer"),
]

users/urls.py
from django.urls import path
from . import views
from .views import dashboard, edit_profile
from .views import (
UserProfileView, RegisterView, UserLoginView,
UserLogoutView, UserPasswordChangeView, HomePageView 
)
# from django .conf import settings
# from django .conf.urls.static import static
app_name = 'users'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  

path('profile/', UserProfileView.as_view(), name='profile'),
path('register/', RegisterView.as_view(), name='register'),
path('login/', UserLoginView.as_view(), name='login'),
path('logout/', UserLogoutView.as_view(), name='logout'),
path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
path('dashboard/', dashboard, name='dashboard'),
path('edit-profile/', edit_profile, name='edit_profile'),
path('clear_avatar/', views.clear_avatar, name='clear_avatar'),  



]

# urlpatterns = [

# ] + static(settings.MEDIA_URL, document_root=settings.media)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Unlock&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <title>{{ title }}</title>
    <style>
        body {
            background-color: black;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li><a class="nav-link text-white" href="{% url 'catalogue:catalogue' %}">Catalogue</a></li>
                        <li><a class="nav-link text-white" href="{% url 'mediaplayer:mediaplayer' %}">Media Player</a></li>
                        <li>
                            <a href="{% url 'cart:cart_summary' %}">
                                <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton" aria-expanded="false">
                                    <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24" height="24">
                                </button>
                            </a>
                        </li>
                        {% if user.is_authenticated %}
                        <li>
                            <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="nav-link text-white" style="border: none; background: none; cursor: pointer;">
                                    Log In
                                </button>
                            </form>
                        </li>
                        {% else %}
                        <li><a class="nav-link text-white" href="{% url 'users:login' %}">Log Out</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block  content%}
    {% endblock  %}
    <footer class="bg-dark text-white py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-3">
                    <h5 class="mb-3">Vinylon</h5>
                    <p>The music that is always with you. Vinyl on offers a wide selection of vinyl records and audio so you can enjoy your favorite tunes anytime, anywhere.</p>
                </div>
                
                <div class="col-md-4 mb-3">
                    <h5 class="mb-3">Полезные ссылки</h5>
                    <ul class="list-unstyled">
                        <li><a href="" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalogue:catalogue' %}" class="text-white">Каталог</a></li>
                        <li><a href="{% url 'users:profile' %}" class="text-white">Личный кабинет</a></li>
                    </ul>
                </div>
    
                <div class="col-md-4 mb-3">
                    <h5 class="mb-3">Следите за нами</h5>
                    <div class="d-flex">
                        <a href="https://www.facebook.com" target="_blank">
                            <img src="{% static 'deps/icons/facebook.svg' %}" alt="Facebook" width="32" class="me-3">
                        </a>
                        <a href="https://www.instagram.com" target="_blank">
                            <img src="{% static 'deps/icons/instagram.svg' %}" alt="Instagram" width="32" class="me-3">
                        </a>
                        <a href="https://www.twitter.com" target="_blank">
                            <img src="{% static 'deps/icons/twitter.svg' %}" alt="Twitter" width="32" class="me-3">
                        </a>
                    </div>
                </div>
            </div>
            
            <div class="text-center mt-3">
                <small>© 2024 Vinylon. Все права защищены.</small>
            </div>
        </div>
    </footer>    

    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script>
        window.addEventListener("scroll", function() {
            const img = document.querySelector("#vinylImg"); 
            const rotation = window.scrollY / 3;
            img.style.transform = `rotate(${rotation}deg)`;
        });
    </script>
    
</body>

</html>