cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update', views.cart_update, name="cart_update"),
]

catalogue/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('', views.CatalogueView.as_view(), name="catalogue"),
    path('<int:pk>/', views.VinylDetail.as_view(), name="vinyldetail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += [
    path('', include('home.urls', namespace='main')),
    path('users/', include('users.urls'), name='users'),
    path('catalogue/', include('catalogue.urls'), name='catalogue'),
    path('cart/', include('cart.urls'), name='cart'),
    path('mediaplayer/', include('mediaplayer.urls'), name='mediaplayer'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Tag(models.Model):
    name = models.CharField(
    max_length=50,
    unique=True,
    verbose_name=_("Название тега"),
    help_text=_("Введите название тега (максимум 50 символов)"),
    )
    class Meta:
        verbose_name = _("Тег")
        verbose_name_plural = _("Теги")
        ordering = ["name"]
    def __str__(self):
        return self.name

class Artist(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Исполнитель"))
    pfp = models.ImageField(upload_to="pfps/", null=True)
    major_info = models.TextField(verbose_name="Основная информация")

    class Meta:
        verbose_name = _("Исполнитель")
        verbose_name_plural = _("Исполнители")
        ordering = ["name"]

    def __str__(self):
        return self.name


class VinylRecord(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("Название альбома"))
    cover = models.ImageField(upload_to="album_covers/", null=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name="artist_name")
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    tags = models.ManyToManyField(Tag, related_name="records", blank=True)
    release_date = models.DateField(null=True, blank=True)
    description = models.TextField(verbose_name=_("Описание альбома"), null=True)

    class Meta:
        verbose_name = _("Винил")
        verbose_name_plural = _("Винилы")
        ordering = ["title"]

    def __str__(self):
        return self.title

catalogue/forms.py
from django import forms
from .models import Tag
from django.db import models

catalogue/views.py
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .models import VinylRecord, Tag, Artist
from django.db.models import Q
from itertools import chain
from icecream import ic
from django.shortcuts import render

class CatalogueView(ListView):
    model = VinylRecord
    template_name = "catalogue/catalogue.html"
    context_object_name = 'vinyls'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get("q")
        vinyls_list = VinylRecord.objects.all()

        if query:
            print(query)
            vinyls_list = VinylRecord.objects.filter(
                Q(title__icontains=query) | Q(artist__name__icontains=query)
            )
        return vinyls_list

    def get_context_data(self, **kwargs: any) -> dict:
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.annotate(num_records=models.Count("records")).order_by("-num_records")[:10]
        context['vinyls'] = self.get_queryset()
        return context


class VinylDetail(DetailView):
    model = VinylRecord
    template_name = "catalogue/vinyl.html"
    success_url = reverse_lazy("cart:cart_summary")

    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['vinyl'] = self.get_object()
        context['vinyls'] = VinylRecord.objects.all()[:10]
        return context

templates/catalogue/catalogue.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<link rel="stylesheet" href="{% static 'deps/css/catalogue.css'%}">

    <form class="tagsForm">
        {% for tag in tags %}
            <input type="button" class="searchTag {{ tag.name }}" value="{{ tag.name }}" isClicked="false">
        {% endfor %}
    </form>
    <div class="main">
        {% for vinyl in vinyls %}
            <div class="vinyl_record">
                <img class="cover" src="{{ vinyl.cover.url }}">
                <h1 class="artist"><a>{{ vinyl.artist.name }}</a></h1>
                <h1 class="title"><a>{{ vinyl.title }}</a></h1>
                <h3 class="artist">{{ vinyl.artist }}</h3>
                <h1 class="price">{{ vinyl.price }} $</h1>
                <a href="{% url 'catalogue:vinyldetail' vinyl.id %}">View Vinyl</a>
                <button type="button" 
                    value="{{vinyl.id}}" 
                    class="btn btn-secondary to_stock" 
                    id="add-cart" data-url="{% url 'cart:cart_add' %}"
                    data-csrf-token="{{ csrf_token }}">
                    Add to cart
                </button>
                <div class="vinyl_tags">
                    {% for tag in vinyl.tags.all %}
                        <div class="tag" data-tag="{{ tag.name }}">{{ tag.name }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if is_paginated %}
            <span>{% trans 'Страница' %} {{ page_obj.number }}{% trans 'из' %} {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'Назад' %}</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">{% trans 'Вперед' %}</a>
            {% endif %}
        {% endif %}
    </div>

    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js'%}"></script>
    <script src="{% static 'deps/js/add-cart.js'%}"></script>
    <script src="{% static 'deps/js/catalogue.js'%}"></script>
{% endblock %}

templates/catalogue/vinyl.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{vinyl.cover.url}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <center>
                        <h5 class="card-title">{{vinyl.title}}</h5>
                        <p class="card-text">{{vinyl.artist}}</p>
                        <p class="card-text">{{vinyl.price}}$</p>
                        <p class="card-text">{{vinyl.description}}$</p>
                        <p>songs:</p>
                        {% for audio in vinyl.audio_files.all %}
                        <div>
                            <h4>{{ audio.title }}</h4>
                            <!-- <audio controls>
                                <source src="{{ audio.audio_file.url }}" type="audio/mpeg">
                                Ваш браузер не поддерживает audio.
                            </audio> -->
                        </div>
                        {% endfor %} 
                        <p class="card-text"><small class="text-body-secondary">ID: {{vinyl.id}}</small></p>
                        <a href="{% url 'catalogue:catalogue' %}">Home</a>
                        <br>
                        <button type="button" value="{{vinyl.id}}" class="btn btn-secondary to_stock" id="add-cart">Add to cart</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

<form class="tagsForm">
    {% for tag in tags %}
    <input type="button" class="searchTag{{ tag.name }}" value="{{ tag.name }}" onclick="buttonClick(this)">
    {% endfor %}
</form>

<div class="main">
    {% for vinyl in vinyls %}
    <div class="vinyl_record">
        <img class="cover" src="{{ vinyl.cover.url }}">
        <h1 class="artist"><a>{{ vinyl.artist.name }}</a></h1>
        <h1 class="title"><a>{{ vinyl.title }}</a></h1>
        <h3 class="artist">{{ vinyl.artist }}</h3>
        <h1 class="price">{{ vinyl.price }} $</h1>
        <button class="to_stock">Add to cart</button>
        <div class="vinyl_tags">
            {% for tag in vinyl.tags.all %}
            <div name="{{ tag.name }}">{{ tag.name }}</div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

<script>
  // проверить если кнопвка нажата

$(document).on('click', '#add-cart', function(e) {
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_add" %}',
        data: {
            vinyl_id: $(this).val(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },
        success: function(json) {
            console.log(json);
        },
        error: function(xhr, errmsg, err) {
            console.log(xhr.status + ": " + xhr.responseText);
        }
    });
});

</script>
{% endblock %}